# Generated by Django 6.0.4 on 2026-05-17 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_permission_role_rolepermission_userrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
