# Generated by Django 6.0.4 on 2026-05-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='module',
            field=models.CharField(default='', help_text="App this permission belongs to, e.g. 'academics'", max_length=50),
        ),
        migrations.AddField(
            model_name='permission',
            name='name',
            field=models.CharField(default='', help_text="Human-readable label, e.g. 'View Results'", max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
    ]
