# Generated by Django 6.0.6 on 2026-06-08 03:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('model_name', models.CharField(blank=True, db_index=True, max_length=120)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('object_repr', models.CharField(blank=True, default='', max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='core_auditl_model_n_3fb686_idx'), models.Index(fields=['actor', 'action'], name='core_auditl_actor_i_7840a5_idx')],
            },
        ),
    ]
