# Generated by Django 6.0.6 on 2026-06-08 02:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramSemesterSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_elective', models.BooleanField(default=False)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum', to='academics.program')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum', to='academics.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_entries', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Curriculum Subject',
                'verbose_name_plural': 'Curriculum Subjects',
                'ordering': ['program', 'semester', 'subject'],
                'constraints': [models.UniqueConstraint(fields=('program', 'semester', 'subject'), name='unique_program_semester_subject')],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=10)),
                ('capacity', models.PositiveSmallIntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='academics.program')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='academics.semester')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['program', 'semester', 'name'],
                'constraints': [models.UniqueConstraint(fields=('program', 'semester', 'name'), name='unique_section_per_program_semester')],
            },
        ),
    ]
