# Generated by Django 6.0.6 on 2026-06-14 05:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_programsemestersubject_section'),
        ('faculty', '0002_facultyleave'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicLeave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academic_leaves', to='academics.academicyear')),
            ],
            options={
                'verbose_name': 'Academic Leave',
                'verbose_name_plural': 'Academic Leaves',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('day_of_week', models.CharField(choices=[('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('faculty_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to='faculty.facultyassignment')),
            ],
            options={
                'verbose_name': 'Routine',
                'verbose_name_plural': 'Routines',
                'ordering': ['day_of_week', 'start_time'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('faculty_assignment', 'day_of_week', 'start_time'), name='unique_routine_slot')],
            },
        ),
    ]
