# Generated by Django 6.0.4 on 2026-05-17 03:06

import datetime
import django.core.validators
import django.db.models.deletion
import fees.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
        ('students', '0004_remove_result_student_remove_result_subject_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestructure',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='course',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='studentfee',
            name='due_amount',
        ),
        migrations.AddField(
            model_name='feestructure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 1, 1)),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='exam_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='library_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='miscellaneous_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Optional catch-all for small charges', max_digits=10),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='semester',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='tuition_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='admin_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 1, 0, 0), help_text='When the student claims payment was made'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('qr', 'QR / eSewa / Khalti'), ('bank', 'Bank Transfer'), ('other', 'Other')], default='cash', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, help_text='Transaction ID, cheque number, or any reference code', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='fee_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_fees', to='fees.feestructure'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='remarks',
            field=models.TextField(blank=True, help_text='Admin notes, e.g. scholarship waiver or late fine'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='year',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='screenshot',
            field=models.ImageField(blank=True, help_text='Payment proof screenshot (required for QR/bank transfers)', null=True, upload_to=fees.models.payment_screenshot_path),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='fees.studentfee'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 1, 1)),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fees', to='students.student'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Copied from FeeStructure.total at time of generation', max_digits=10),
        ),
    ]
