# Generated by Django 6.0.4 on 2026-05-17 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('fees', '0002_remove_feestructure_amount_and_more'),
        ('students', '0004_remove_result_student_remove_result_subject_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feestructure',
            options={'ordering': ['faculty', 'year', 'semester']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-paid_at']},
        ),
        migrations.AlterModelOptions(
            name='studentfee',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='feestructure',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='academics.faculty'),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('faculty', 'year', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='studentfee',
            unique_together={('student', 'fee_structure')},
        ),
    ]
