# Generated by Django 6.0.4 on 2026-05-21 15:12

import django.core.validators
import django.utils.timezone
import fees.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_alter_feestructure_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='due_date',
            field=models.DateField(default=fees.models._default_due_date),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the student claims payment was made'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='due_date',
            field=models.DateField(default=fees.models._default_due_date),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Snapshotted from FeeStructure.total at generation time', max_digits=10),
        ),
    ]
