# Generated by Django 6.0.4 on 2026-05-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='access_jti',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
