# Generated by Django 6.0.4 on 2026-05-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_remove_notice_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-date_posted']},
        ),
        migrations.AddField(
            model_name='notice',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Deactivate instead of deleting old notices'),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_audience',
            field=models.CharField(choices=[('all', 'Everyone'), ('students', 'Students Only'), ('teachers', 'Teachers Only'), ('finance', 'Finance Only')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='notice',
            name='type',
            field=models.CharField(choices=[('fee', 'Fee'), ('exam', 'Exam'), ('holiday', 'Holiday'), ('emergency', 'Emergency'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
