# notices/admin.py
"""
RBAC-aware admin for the notices app.

Permission codes:
  notices.view_notice    → PermissionCodes.NOTICES_VIEW
  notices.manage_notice  → PermissionCodes.NOTICES_MANAGE  (add/change/delete)

NoticeRead is read-only analytics — only admins/superusers need to see it.
"""
from django.contrib import admin

from auth_core.admin_base import RBACAdmin, ReadOnlyRBACAdmin
from notices.models import Notice, NoticeRead


# ─────────────────────────────────────────────────────────────────────────────
# NoticeAdmin
# ─────────────────────────────────────────────────────────────────────────────

@admin.register(Notice)
class NoticeAdmin(RBACAdmin):
    """
    Notice board management.

    Permission codes:
      view   → notices.view_notice     (auto-generated)
      add    → notices.manage_notice   (PermissionCodes.NOTICES_MANAGE)
      change → notices.manage_notice
      delete → notices.manage_notice
    """

    add_permission    = "notices.manage_notice"
    change_permission = "notices.manage_notice"
    delete_permission = "notices.manage_notice"

    list_display   = ["title", "type", "priority", "target_audience", "is_active", "date_posted"]
    list_filter    = ["type", "priority", "target_audience", "is_active"]
    search_fields  = ["title", "content"]
    ordering       = ["-date_posted"]
    readonly_fields = ["date_posted"]
    actions        = ["deactivate_notices", "activate_notices"]

    @admin.action(description="🔕 Deactivate selected notices")
    def deactivate_notices(self, request, queryset):
        if not self.has_change_permission(request):
            self.message_user(request, "Permission denied.", level="error")
            return
        updated = queryset.update(is_active=False)
        self.message_user(request, f"{updated} notice(s) deactivated.")

    @admin.action(description="📣 Activate selected notices")
    def activate_notices(self, request, queryset):
        if not self.has_change_permission(request):
            self.message_user(request, "Permission denied.", level="error")
            return
        updated = queryset.update(is_active=True)
        self.message_user(request, f"{updated} notice(s) activated.")


# ─────────────────────────────────────────────────────────────────────────────
# NoticeReadAdmin — read analytics; always read-only
# ─────────────────────────────────────────────────────────────────────────────

@admin.register(NoticeRead)
class NoticeReadAdmin(ReadOnlyRBACAdmin):
    """
    Read-tracking analytics for notices.
    Strictly read-only — the table is populated by the API, not the admin.

    Permission codes:
      notices.view_noticeread  (auto-generated by ReadOnlyRBACAdmin)
    """

    list_display  = ["notice", "user", "read_at"]
    list_filter   = ["notice__type"]
    search_fields = ["user__username", "notice__title"]
    ordering      = ["-read_at"]
