# Generated by Django 6.0.6 on 2026-06-20 04:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_academicleave_routine'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='academics.academicyear')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='academics.program')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='academics.semester')),
            ],
            options={
                'verbose_name': 'Fee Structure',
                'verbose_name_plural': 'Fee Structures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_optional', models.BooleanField(default=False)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='fees.feestructure')),
            ],
            options={
                'verbose_name': 'Fee Component',
                'verbose_name_plural': 'Fee Components',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='feestructure',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('academic_year', 'program', 'semester', 'name'), name='unique_fee_structure'),
        ),
        migrations.AddConstraint(
            model_name='feecomponent',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('fee_structure', 'name'), name='unique_component_per_structure'),
        ),
    ]
