# Generated by Django 6.0.6 on 2026-06-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_academicleave_routine'),
        ('fees', '0004_payment_is_refunded_payment_refund_reason_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studentfee',
            name='unique_student_fee_structure',
        ),
        migrations.AddConstraint(
            model_name='studentfee',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('student', 'academic_year', 'program', 'semester'), name='unique_student_fee_per_term'),
        ),
    ]
