# Generated by Django 6.0.6 on 2026-06-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_remove_studentfee_unique_student_fee_structure_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-generated_at'], 'verbose_name': 'Receipt', 'verbose_name_plural': 'Receipts'},
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='issued_at',
            new_name='generated_at',
        ),
        migrations.AddField(
            model_name='receipt',
            name='pdf_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
