# Generated by Django 6.0.4 on 2026-05-17 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='course',
        ),
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, help_text='Short unique code, e.g. CS201', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.faculty'),
        ),
        migrations.AddField(
            model_name='subject',
            name='full_marks',
            field=models.PositiveSmallIntegerField(default=100, help_text='Total marks for this subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='pass_marks',
            field=models.PositiveSmallIntegerField(default=40, help_text='Minimum marks required to pass'),
        ),
        migrations.AddField(
            model_name='subject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
