# Generated by Django 6.0.4 on 2026-05-19 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_examroutine_options_alter_result_options_and_more'),
        ('subjects', '0002_remove_subject_course_subject_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['faculty', 'name']},
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(default='ISC', help_text='Short unique code, e.g. CS201', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.faculty'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(default=3, max_length=150),
            preserve_default=False,
        ),
    ]
