# Generated by Django 6.0.4 on 2026-05-19 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_examroutine_options_alter_result_options_and_more'),
        ('subjects', '0003_alter_subject_options_alter_subject_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.faculty'),
        ),
    ]
