# Generated by Django 6.0.6 on 2026-06-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_programsemestersubject_section'),
        ('exams', '0002_exam_examschedule_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exam',
            name='unique_exam_per_program_semester_type',
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('academic_year', 'program', 'semester', 'exam_type', 'name'), name='unique_exam_identity'),
        ),
    ]
