
from django.contrib import admin

from auth_core.admin_base import RBACAdmin, ReadOnlyRBACAdmin
from auth_core.models import UserProfile, UserSession, TokenBlacklist, AuditLog

@admin.register(UserProfile)
class UserProfileAdmin(RBACAdmin):
    list_display    = ["user", "phone", "created_at"]
    search_fields   = ["user__username", "user__email", "phone"]
    readonly_fields = ["created_at", "updated_at"]

@admin.register(UserSession)
class UserSessionAdmin(ReadOnlyRBACAdmin):
    """
    Active session viewer. Always read-only — sessions are managed by
    AuthService and must never be mutated directly via the admin.

    Permission codes:
      auth_core.view_usersession   (auto-generated by ReadOnlyRBACAdmin)
    """

    list_display    = ["user", "jti_short", "ip_address", "is_active", "created_at", "closed_at"]
    list_filter     = ["is_active"]
    search_fields   = ["user__username", "jti", "ip_address"]
    readonly_fields = ["jti", "ip_address", "user_agent", "created_at", "last_seen_at", "access_jti"]

    @admin.display(description="JTI (prefix)")
    def jti_short(self, obj):
        return f"{obj.jti[:12]}…"


# ─────────────────────────────────────────────────────────────────────────────
# TokenBlacklistAdmin — read-only security record
# ─────────────────────────────────────────────────────────────────────────────

@admin.register(TokenBlacklist)
class TokenBlacklistAdmin(ReadOnlyRBACAdmin):
    """
    Token blacklist viewer. Immutable — written only by AuthService.logout().

    Permission codes:
      auth_core.view_tokenblacklist
    """

    list_display    = ["jti_short", "blacklisted_at", "expires_at"]
    readonly_fields = ["jti", "blacklisted_at", "expires_at"]

    @admin.display(description="JTI (prefix)")
    def jti_short(self, obj):
        return f"{obj.jti[:12]}…"


# ─────────────────────────────────────────────────────────────────────────────
# AuditLogAdmin — immutable, read-only forever
# ─────────────────────────────────────────────────────────────────────────────

@admin.register(AuditLog)
class AuditLogAdmin(ReadOnlyRBACAdmin):
    """
    Security audit log viewer. Audit records are immutable by design —
    deleting or editing them would undermine the audit trail.

    ReadOnlyRBACAdmin blocks add / change / delete at the class level.

    Permission codes:
      auth_core.view_auditlog
    """

    list_display    = ["event", "user", "ip_address", "created_at"]
    list_filter     = ["event"]
    search_fields   = ["user__username", "ip_address", "event"]
    readonly_fields = ["user", "event", "ip_address", "user_agent", "metadata", "created_at"]
