# Generated by Django 6.0.4 on 2026-05-17 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='code',
        ),
    ]
